arrow-py/arrow

arrow/__init__.py
setup.py

Use __version__ from module to have them same.

Use __version__ from module.

---

arrow/locales.py

In Chinese, only  Quantitative seconds makes sense.

Chinese locale: Quantitative seconds

---

arrow/locales.py

Fix Finnish grammar to look more natural.

Fix Finnish grammar

---

arrow/arrow.py

Hi,
You have a small typo in documentation.
Regards.

Fix typo timezone

---

arrow/parser.py
tests/formatter_tests.py
tests/locales_tests.py
tests/parser_tests.py

There is a previous PR (https://github.com/crsmithdev/arrow/pull/172) that currently has merge conflicts. @crsmithdev do you know if we can merge either this one or the one by @zed ?
Closes #61

Parse localized month names

---

arrow/arrow.py
arrow/parser.py

A method not using cls or self should be defined as a static method
(not a class method)

Cleanup class methods definition

---

arrow/locales.py

Missing first element in month and day lists

Fix Czech locale

---

arrow/locales.py
arrow/util.py

All tests pass after this little change.

Remove two modules that were imported but unused

---

arrow/locales.py

added locale support for my mother-tongue, Bengali.
couldn't comprehend __**ordinal_day_re**__ regular-expression enough to include it translated.
Thanks in advance for reviewing and merging.

Added Bengali Locale support ['bn', 'bn_bd', 'bn_in']

---

arrow/arrow.py
tests/arrow_tests.py

1.5 months no longer returns 'in 1 months'

---

arrow/locales.py

https://en.wikipedia.org/wiki/Romansh_language

Adds romansh locale

---

HISTORY.md
arrow/locales.py
tests/locales_tests.py

Hi! I added the Esperanto locale.
I hope you like it!

Adding Esperanto (eo) locale.

---

README.rst
arrow/parser.py
docs/index.rst
tests/parser_tests.py

Fixes #307 and doc changes to address #291

Adds support for tz offsets without minutes

---

arrow/parser.py
tests/factory_tests.py

The branch is named twitter because I had trouble parsing dates returned by twitter API, which
look like:  Fri Apr 08 19:19:24 +0000 2016
Fixes #281 and #273

arrow.get(): Implement d, ddd and ddd

---

arrow/locales.py

Slovenian locale added

---

arrow/arrow.py

Remove duplicate code

---

arrow/arrow.py
tests/arrow_tests.py

I’m not terribly happy with the implementation - I don’t grok why
dateutil handles some values (negatives and zeroes) the way it does,
but I figure this is good to generate discussion anyway.

Implement weekday shifting for #64

---

arrow/locales.py

Fixes a typo in the Swiss German translation

---

arrow/locales.py
tests/locales_tests.py

This PR will add Indonesian Locale to Arrow. Tests are included with the PR.

Add Indonesian Locale to Arrow

---

arrow/locales.py

This fixes #459:
* renamed AustriaLocale to AustrianLocale
* changed name of first month to "Jänner"

Changed AustriaLocale

---

arrow/__init__.py

Bumps the version to 0.12.1 so we can have the wheels fix uploaded to pypi.

Bump version to 0.12.1

---

arrow/factory.py

Takes @smontanaro documentation tweak from https://github.com/crsmithdev/arrow/pull/485.

Include ZZZ in format example as a hint

---

setup.py

Fixes #171.
The first part is dealt with in PR #472.

Add tests_require=['chai']

---

arrow/arrow.py
tests/arrow_tests.py

Addressing the feature request in #548, @TroyStacer and I have implemented the isbetween functionality in Arrow that functions similarly to the [isBetween function in Moment.js](https://momentjs.com/docs/#/query/is-between/).
Closes: #548

Add is_between functionality

---

arrow/locales.py
tests/locales_tests.py

Since @TroyStacer and I were already working on fixing issue #541 in Humanize, we thought we would tackle bug #416 as well since the PR and issue for it has been stale since mid 2017.
Fixes: https://github.com/crsmithdev/arrow/issues/416
The original PR for this issue (https://github.com/crsmithdev/arrow/pull/417) did not seem to fully address the issue and had failing tests, so we decided to open a new PR with fresh changes and updates.

Improved humanize behavior for near-zero durations

---

.travis.yml
Makefile
arrow/parser.py

Fix SyntaxWarning due to escape sequences and enable Python 3.8 build

---

docs/conf.py
docs/index.rst

Quick update of supported python versions in main docs in preparation for 0.14.0. I'll get @crsmithdev to push a new version to readthedocs when the pypi release happens.

Docs update for 0.14.0

---

arrow/factory.py

This is a follow-up to: https://github.com/crsmithdev/arrow/pull/621
I just cleaned up some of the conditionals. @systemcatch we should definitely push a release of `0.14.4` tomorrow with this fix and the `install_requires` tweaks.

Tweaked factory kwargs handling

---

arrow/locales.py

Add Afrikaans locale

---

arrow/locales.py

Update japanese translations for week(s)

Update Japanese translations for week(s)

---

.travis.yml
CHANGELOG.md
tests/parser_tests.py

Temporary fix for: https://github.com/crsmithdev/arrow/issues/668

Add Travis config for Windows

---

CHANGELOG.rst
MANIFEST.in
docs/index.rst
docs/releases.rst

Test it out:
```bash
$ make docs
$ python3 -m http.server 8000 --directory docs/_build/html/
```
Closes: https://github.com/crsmithdev/arrow/issues/660

Added CHANGELOG to docs

---

arrow/factory.py
arrow/util.py
tests/factory_tests.py
tests/util_tests.py

Allow factory.get() to create from a ISO calendar tuple

---

.pre-commit-config.yaml
arrow/parser.py
requirements.txt

Black 19.10 was released this week, so I took the time to upgrade some of the dependencies and re-run the new version of black.

Upgraded dependencies and re-run black

---

arrow/locales.py

add week to the dutch/nl locale

---

arrow/locales.py
tests/locales_tests.py

Added Hong Kong (zh_hk) locale with its unit test

Added Hong Kong (zh_hk) locale

---

.travis.yml
arrow/arrow.py
arrow/util.py
tests/arrow_tests.py
tests/util_tests.py

Replaces: https://github.com/crsmithdev/arrow/pull/744

Fixed arrow.get with a timestamp and a timezone string

---

docs/index.rst
tests/arrow_tests.py

Added comments explaining the new tests and referenced the correct issues.
Replaces #732 
Closes #376 
Closes #551

Add Arrow DST tests based on two false positives

---

.travis.yml

Force pip3 wherever it is available to prevent installation on Python 2.7 on OS X, in particular (ref: https://travis-ci.org/crsmithdev/arrow/builds/635815822).

Force use of pip3 on Travis

---

.github/FUNDING.yml
.pre-commit-config.yaml
.travis.yml
requirements.txt

Added sponsorship info and update dependencies

Added sponsorship info and update dependencies

---

docs/conf.py
docs/index.rst

Change GH watch button to star button

---

arrow/locales.py
tests/conftest.py
tests/test_arrow.py
tests/test_factory.py
tests/test_formatter.py
tests/test_locales.py
tests/test_parser.py

Moving all classes to have pytest fixtures
The lang_locale_fixture is a bit of a hack, but this was the easiest way I thought of instead of changing every single class. Open to suggestions to change it!
Cheers!
Closes: #760

Convert test setup methods to pytest fixtures

---

arrow/locales.py
tests/test_locales.py

Also adds missing tests for timeframes
- [n/a] 📚 Updated **documentation** for changed code.

Add week support for zh_tw locale

---

Makefile
arrow/formatter.py
tests/test_formatter.py

Fix bug with Python 2.7 and the new "x" token.

Fix x formatting token on Python 2.7

---

arrow/locales.py

Added support for week in swedish locale.

---

.github/pull_request_template.md
README.rst
tests/test_parser.py

Improved contributing docs to better guide new contributors and added linting checks to PR template. Added Open Collective info to README.
Replaces: https://github.com/crsmithdev/arrow/pull/767

Added better contributing docs to README and improved PR template

---

README.rst

GitHub seems to incorrectly display sublists in RST, so I just placed the sublist options inline.

Fix RST formatting bug in README

---

.pre-commit-config.yaml
requirements.txt
tests/test_formatter.py
tests/test_parser.py

Update dependencies and parametrize TZ list.

Bump dependencies and parametrize TZ list

---

.github/workflows/continuous_integration.yml
tox.ini

The tox-gh-actions library (https://github.com/ymyzk/tox-gh-actions) seems to have made a change recently that changed the way we need to run our tests. I have made the changes to make the tests work again.

Fix tests on GH actions

---

arrow/locales.py
tests/test_locales.py

Add support for week for the Slovak locale, fix a translation error (“druhý” in Slovak means “second” like “the one after the first one”, not a short time unit; as well as “pár” means “a couple” and not a specific number) and complete the tests to cover all time units and all cases of a Slavic language.

Add support for week for the Slovak locale and complete the tests

---

arrow/locales.py
tests/test_locales.py

Adds French Canadian Locale, with updated unit tests. Adds different month abbreviation for Fr_CA. 
Closes #436

Add French Canadian locale

---

arrow/locales.py
tests/test_locales.py

- [N/A] 📚 Updated **documentation** for changed code.
Add Hebrew translation for "weeks". Currently I catch the ValueError in my codebase to prevent arrow from crashing when trying to humanize weeks :)

Add weeks translation for Hebrew

---

.github/workflows/continuous_integration.yml

Attempt fix at CI

---

CHANGELOG.rst
README.rst

Some documentation links point directly to latest, but it is best to just point to the readthedocs.io link and let it decide whether to go stable or latest.

Tweak documentation links

---

arrow/locales.py
tests/test_locales.py

- [ x ] 🧪 Added **tests** for changed code.
- [ x ] 🛠️ All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ x ] 🧹 All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ x ] ⏩ Code is **up-to-date** with the `master` branch.
Added week and weeks timeframes to the czech locale. Documentation is not affected.
Closes: #815

Added week and weeks timeframes for Czech locale

---

.github/workflows/continuous_integration.yml

Simplify CI pipeline to prevent duplication across matrix OSes.

Simplify CI pipeline

---

arrow/parser.py
arrow/util.py
tests/test_formatter.py
tests/test_parser.py
tests/test_util.py

Closes: https://github.com/crsmithdev/arrow/issues/446
Replaces https://github.com/crsmithdev/arrow/pull/820 due to GitHub glitch.

Fix arrow.get functionality when weekday is parsed alone

---

.github/workflows/continuous_integration.yml

Add cache to CI pipeline

---

tox.ini

Change Tox terminology from whitelist to allowlist to be more inclusive.

Change Tox terminology

---

docs/index.rst

Update docs for timezone abbreviations (PDT, MST, CET etc)

---

.pre-commit-config.yaml
requirements.txt
tox.ini

The release of iSort v5.0 allows us to remove a number of pre-commit packages in favor of a default pre-commit solution provided by the iSort folks. I also took the liberty to upgrade a number of pre-commit packages and test dependencies (including a major bump to Pytest).

Remove deprecated packages from pre-commit and upgrade dependencies

---

.pre-commit-config.yaml
arrow/api.py
arrow/arrow.py
arrow/factory.py
arrow/locales.py
arrow/parser.py
tests/test_arrow.py
tests/test_factory.py
tests/test_parser.py
tox.ini

Black now has an opinion about docstrings and removes trailing and leading whitespace in docstrings. Also, I am enforcing a minimum tox version since the keyword `whitelist_exteranls` has been replaced by `allowlist_externals`.

Upgrade black and enforce minimum Tox version

---

.github/workflows/continuous_integration.yml

Exclude pypy3 from Windows

---

arrow/locales.py
tests/test_locales.py

This adds weeks and meridians to Tagalog.
Along with a full battery of tests.

Add weeks and expand on tests for Tagalog locale

---

arrow/parser.py
tests/test_parser.py

Fixed a case sensitivity issue reported in #851, and added missing `asserts`!
Closes: https://github.com/arrow-py/arrow/issues/851

Add case normalization to day of week parsing

---

arrow/locales.py

Sources:
- https://www.ub.edu/cub/llistat_ab.php?taula=DS&ordre=mots_t&idioma=1
- https://aplicacions.llengua.gencat.cat/llc/AppJava/index.html?action=Principal&method=detall&input_cercar=abreviatures+mesos&numPagina=1&database=FITXES_PUB&idFont=8402&idHit=8402&tipusFont=Fitxes+de+l%2527Optimot&numeroResultat=1&databases_avansada=&categories_avansada=&clickLink=detall&titol=abreviatures+dels+mesos+de+l%2527any&tematica=&tipusCerca=cerca.normes

Include day and month abbreviations for Catalan

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/workflows/continuous_integration.yml

In the past, we have seen people struggle to follow the PR and issue templates (e.g. place things inside of the HTML comments), so I have cleaned them up to make them a bit easier to navigate and use.

Cleanup issue and PR templates for easier use

---

arrow/locales.py
contributors/kosuke316.md
tests/test_locales.py

Correct mistakes in Japanese locale

---

arrow/constants.py
tests/test_parser.py

Closes: https://github.com/arrow-py/arrow/issues/880

Fix MAX_TIMESTAMP on Windows

---

arrow/arrow.py
arrow/constants.py
arrow/util.py
tests/test_arrow.py
tests/test_util.py

Hey! I have completed the implementation for fromordinal method along with tests and also added the timespec arg for isoformat method. I look forward to your feedback on this, thanks.
Closes: #840

Implemented new fromordinal method and added new timespec arg to isoformat.

---

arrow/arrow.py
arrow/factory.py
arrow/locales.py
arrow/parser.py
arrow/util.py

A series of independent commits to modernize the code to Python 3.6+
1. simplify chained conditions
2. fix method docstrings (missing arguments)
3. convert map to dict comprehension
4. refactor the describe_multi method
5. better repr of strings: `'{val}'` to `{val!r}`
6. refactor `isinstance(var, typea) or isinstance(var, typeb)` to `isinstance(var, (typea, typeb))`

Modernize code for Python 3.6+

---

.pre-commit-config.yaml
requirements.txt
tests/test_arrow.py

Implement test mentioned by @eumiro in https://github.com/arrow-py/arrow/pull/903#discussion_r549204240 and fix flake8 pointless comparison errors.

Fix linting CI and tweak is_between tests

---

tests/test_arrow.py

Closes: https://github.com/arrow-py/arrow/issues/890

Tweak day test and xfail month test for humanize

---

arrow/arrow.py
arrow/constants.py
arrow/formatter.py
arrow/util.py
tests/test_parser.py

Refactor to remove Python2-specific numeric hacks that are no more needed in Python3.

Remove redundant Python2 numeric relics

---

.pre-commit-config.yaml
LICENSE
README.rst
docs/conf.py
requirements.txt
tox.ini

Update dependencies and add sphinx type extension to bake type annotations into docs.
Closes: https://github.com/arrow-py/arrow/issues/899

Update dependencies and add type annotations to sphinx docs

---

arrow/arrow.py

Remove usage of dateutil enfold()

---

arrow/locales.py

The rules for German timeframes for only_distance=True where incomplete.
This PR fixes several missing cases in GermanBaseLocale.

Fix German time frames

---

README.rst
docs/index.rst

Remove and/or update references to `timestamp` property.
Closes: https://github.com/arrow-py/arrow/issues/928

Remove timestamp property references in examples

---

arrow/constants.py

Fixes OverflowError on 32-bit Linux systems.
Closes: https://github.com/arrow-py/arrow/issues/930

Fix overflow on 32-bit Linux systems

---

tox.ini

Just one digit makes all the difference.

Lower coverage requirement to 99% until humanize xfail month tests are fixed

---

arrow/api.py

- [x ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ x] ⏩  Code is **up-to-date** with the `master` branch.
Fixes https://github.com/arrow-py/arrow/issues/942

Restore datetime constructor type acceptability in factory.get()

---

arrow/locales.py
tests/test_locales.py

Add Croatian locale

---

arrow/locales.py
tests/test_locales.py

Add Lithuanian locale

---

arrow/locales.py
tests/test_locales.py

Adds another locale: Latvian. :)

Add Latvian locale

---

arrow/locales.py
tests/test_locales.py

Adds Latin locale. :)
Unfortunately I didn't find abbreviations for the week days, therefore the full forms are listed there.

Add Latin locale

---

arrow/locales.py
tests/test_locales.py

Add Malay locale

---

README.rst
arrow/api.py
arrow/arrow.py
arrow/constants.py
arrow/factory.py
arrow/formatter.py
arrow/locales.py
arrow/parser.py
tests/test_locales.py
tests/test_parser.py

Closes: https://github.com/arrow-py/arrow/issues/952

Standardize locales and improve locale validation

---

arrow/locales.py
tests/test_locales.py

Adds Maltese locale. :)
Also fixes two white spaces in Malay locale.

Add Maltese locale

---

arrow/constants.py
arrow/locales.py
tests/test_arrow.py
tests/test_locales.py

Add Luxembourgish locale :) Here is the [reference](https://www.scriptsource.org/cms/scripts/page.php?item_id=entry_detail&uid=zvb7ca9klg).
Note:  `hook id: black` is failed when running test locally at first place :(

add Luxembourgish locale

---

arrow/locales.py

Adds variants to locale names: hi-in, mt-mt and sr-rs.

[locales] expand locale name variants

---

tests/test_locales.py

Adds tests for ChineseCN locale.
Closes #960

Add tests for ChineseCN locale. (#960)

---

.pre-commit-config.yaml

Updated precommit revisions for:
- isort
- pyupgrade
- black

Update .pre-commit-config.yaml to newest revisions of hooks.

---

arrow/locales.py

Not sure if "ua" is a typo here, so I added "uk" additionally.

add ukrainian locale name variant

---

arrow/locales.py

Added Specificity to Nepali Years Timeframe Unit

---

arrow/locales.py

In Catalan, '1' for numbers is written as 'un'

---

arrow/locales.py
tests/test_locales.py

Refactored Icelandic Locale for Future Dehumanize Support (#961 and #970).

Refactor of Icelandic Locale For Dehumanize Support

---

arrow/locales.py
tests/test_locales.py

This is a refactor of the Hebrew Locale for future dehumanize support. See #1028 for why we are electing to use a string representation of a number for some of the keys. Note on the changed test cases, we never call format_relative with a delta of 1 on plural units, so having test cases that use this pattern, and a function checking for this pattern, isn't necessary.

Hebrew Locale Refactor For Dehumanize Support

---

arrow/locales.py
tests/test_locales.py

Czech Locale has been refactored for future Dehumanize support. This will serve as a baseline for the Slovak locale refactor as well.

Refactor of Czech Locale For Dehumanize Support

---

arrow/locales.py

Refactored Slovak locale to support dehumanize. Similar to Czech locale refactor #1021.

Refactor of Slovak Locale For Dehumanize Support

---

arrow/locales.py
tests/test_locales.py

Refactored Finnish Locale for future dehumanize support.

Refactored Finnish Locale

---

arrow/factory.py
tests/test_factory.py

Add support for Decimal type as input to arrow.get
Closes #1033

Add support for Decimal as input to arrow.get.

---

arrow/locales.py
tests/test_locales.py

Added `week`/`weeks` and `quarter`/`quarters` timeframes for Indonesian locale.

Add weeks and quarters timeframes for Indonesian locale

---

.github/workflows/continuous_integration.yml
.pre-commit-config.yaml
Makefile
arrow/locales.py
requirements/requirements-docs.txt
requirements/requirements-tests.txt
requirements/requirements.txt
tox.ini

Break up requirements-dev.txt into 3 different files:
1. requirements.txt - main package dependencies specified in setup.py
2. requirements-docs.txt - doc dependencies
3. requirements-tests.txt - test dependencies

Break up requirements.txt into multiple requirements files

---

arrow/locales.py
tests/test_locales.py

In Norwegian, there should be a period after the day of the month.

Fix ordinals for norwegian languages

---

arrow/locales.py
tests/test_locales.py

Changes for Danish locale:
- Correct typos for relative humanizations.
- Use correct ordinal number format.
- Add tests.

Fix issues and add tests for Danish language

---

arrow/constants.py
arrow/locales.py
tests/test_arrow.py
tests/test_locales.py

Adds Georgian to arrow locales. :)

Add Georgian locale

---

arrow/constants.py
arrow/locales.py
tests/test_locales.py

Add Amharic local to arrow ([references](https://unicode-org.github.io/cldr-staging/charts/37/verify/dates/am.html)).

Add Amharic Locale

---

.pre-commit-config.yaml
arrow/arrow.py
arrow/constants.py
tests/test_arrow.py
tests/test_factory.py
tests/test_parser.py
tox.ini

Fix failing CI lint task due to flake8 plugin upgrades.

Fix failing CI lint task

---

arrow/constants.py
arrow/locales.py
tests/test_arrow.py
tests/test_locales.py

Adds Laotian locale. (Wasn't sure if it should be added to the lists in constants.py and test_arrow.py.)

Add Laotian locale

---

.github/workflows/continuous_integration.yml

Updates versions of Github's CI Actions.

Update Github CI Actions.

---

arrow/locales.py
tests/test_locales.py

Update the Finnish localization to use the correct declension for singular second and day, and remove the "muutama" from the plural seconds which seems to be old mishap with localization.

Update Finnish locale

---

arrow/locales.py
tests/test_locales.py

Add week and weeks keywords to HungarianLocale timeframes.

Fix hungarian locale

---

arrow/locales.py

Added two lines to Finnish locale for the humanization of the 'week' granularity. `arrow.utcnow().shift(weeks=2).humanize(locale='fi')` used to raise `ValueError`.

Added translation for weeks in Finnish locale

---

arrow/locales.py

Hopefully a trivial change that doesn't require tests, etc

Add weeks to catalan locale

---

arrow/locales.py

Revert "Improve FA locale to cover more ts #1166" 
