arrow-py/arrow

arrow/formatter.py
arrow/parser.py
tests/formatter_tests.py
tests/parser_tests.py

This pull request fixes the bug referenced in #83.
Now, fractional seconds are properly handled and not considered as microseconds:
```python
arrow.get('2013-05-05T12:30:45.2+0030').datetime
datetime.datetime(2013, 5, 5, 12, 30, 45, 200000, tzinfo=tzoffset(None, 1800))
arrow.get('2013-05-05T12:30:45.002+0030').datetime
datetime.datetime(2013, 5, 5, 12, 30, 45, 2000, tzinfo=tzoffset(None, 1800))
arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSS ZZ')
'2013-05-05 12:30:45.002 +00:30'
arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSSSS ZZ')
'2013-05-05 12:30:45.00200 +00:30'
arrow.get('2013-05-05T12:30:45.002+0030').format('YYYY-MM-DD HH:mm:ss.SSSSSS ZZ')
'2013-05-05 12:30:45.002000 +00:30'
```

Fix for ISO parsing and formatting for fractional seconds

---

README.md
arrow/arrow.py
docs/index.rst
tests/arrow_tests.py

Everything else in arrow has the most sane defaults ever, but getting
a human readable string from format requires a format. Just default to
something.

Give format a default parameter

---

arrow/locales.py

In Dutch, it is common to use "3 uur" (singular noun) when referring to 3 hours, while we use plural forms for other time frames (days, minutes, seconds, and so on).

Use correct Dutch wording for "hours"

---

arrow/locales.py

English locale is used in more countries than the US.
https://pic.dhe.ibm.com/infocenter/ratdevz/v7r5/index.jsp?topic=%2Fcom.ibm.etools.est.doc%2Ftopics%2Frxmlenaloccp.html
Since this is a library used in multiple projects, I believe it should contain at least the most common locales.
(I encountered a problem using "en_GB" locale before proposing this change)

Complete the list of english locales

---

arrow/arrow.py
tests/arrow_tests.py

Currently, comparison of `Arrow` to any type except `Arrow` and `datetime.datetime` always gives `False`:
```python
>>> arrow.Arrow(2015, 1, 1) > datetime.date(2015, 1, 2)
False
>>> arrow.Arrow(2015, 1, 1) < datetime.date(2015, 1, 2)
False
```
I think this can be misleading, and suggest raising a `TypeError` instead (this is also what `datetime.datetime` does).

Raise TypeError on invalid comparison

---

arrow/parser.py
tests/parser_tests.py

It appears the documented 'h' and 'hh' tokens are not currently working, the following Pull Request is an attempt at fixing that.
Before the fix:
```python
>>> arrow.get("5 PM", "h A")
<Arrow [0001-01-01T12:00:00+00:00]>
```
After the fix:
```python
>>> arrow.get("5 PM", "h A")
<Arrow [0001-01-01T17:00:00+00:00]>
```

Parse lower-cased 'h'

---

arrow/locales.py

This makes it sound a little more natural. Dutch people will not say "6 uren geleden", but "6 uur geleden". Similarly: "over 17 jaar", not "over 17 jaren". Even though the plurals are correct.
Lastly, the common abbrev for March is "mrt", not "maa".

Slight modifications to Dutch locale.

---

arrow/arrow.py
requirements.txt
tests/arrow_tests.py

Hi,
I have added a `for_json` method to the `arrow.Arrow` class then serialize the `Arrow` instances inside a dictionary will be possible.
``` python
>>> import simplejson as json
>>> json.dumps({'start': arrow.get(0)}, for_json=True)
'{"start": "1970-01-01T00:00:00+00:00"}'
```
Please review it. Thanks.

Add "for_json" method to support simplejson serialization.

---

arrow/locales.py
tests/locales_tests.py

includes special support for "couple of years/months/days/hours" as they are different words in Hebrew.

Add Hebrew Locale

---

arrow/parser.py
tests/parser_tests.py

arrow.get() requires an exact string match for the month name and month abbreviation tokens (MMM and MMMM).  Thus Feb matches MMM but feb and FEB do not.  This is straightforward to work around in calling code, but seemed as though it might be common enough to warrent a patch.
Note that this does not work with non english locales (due to using calendar to build the regex rather than the parser locale) but as far as I can tell this isn't a regression.

Case insensitive month match

---

setup.py

I hit an issue when trying to install arrow with python3.  It defaulted to trying the interpret the README via an ascii encoding, when it's really utf-8 encoded.  This approach should work on both python2 and python3.

Be explicit about encoding when reading in README.

---

arrow/arrow.py

It was 'ceil' in usage example.

Fix typo in 'Arrow.floor' docstring

---

arrow/locales.py

This is following the rules of the Real Academia de la Lengua Española.

Spanish locale: `Miercoles` should have acute accent

---

arrow/arrow.py
tests/arrow_tests.py

I found myself wanting a span of N years in some code I was writing. I was able to do this with:
```python
end = start.replace(years=+num_years).ceil('year')
```
...but I was surprised that I couldn't just do:
```python
start, end = start.span('year', num_years)
```
This patch adds a count argument to the span method so that the above example does the right thing. It turned out to be trivial to implement and I made the argument optional and defaulting to 1 so that it's backwards-compatible.
I added a single unit test, I'm not sure how thorough you like to be here.

Add count argument to span method

---

arrow/locales.py

I've fixed capitalization on turkish and arabic dialects because these dialects was written in uppercase so get_locale("tr_tr") fails. Also I added two new locales, basque and catala, two languages from spain.

A couple of dialect fixes and two new languages

---

arrow/parser.py
tests/parser_tests.py

Note that this PR merely corrects the narrow issue observed in #219. Many of the more esoteric features of ISO 8601 are still absent. For example, [fractional portions are contemplated for *any time member*](https://en.wikipedia.org/wiki/ISO_8601#Times). Also, the fractional portion delimiter can be a period (`.`) or a comma (`,`). In other words, the following should be equivalent:
* `2015-05-01T12.2525Z`
* `2015-05-01T12:15,15Z` (note the comma)
* `2015-05-01T12:15:09Z`
Addressing *those* would require a significant change to `parse_iso()`. To be fair, I don't know if *any* library is actually fully ISO 8601 compliant. `dateutils` for example only supports fractional minutes with the period delimiter:
```py
>>> from dateutil.parser import parse
>>> parse('2015-05-01T12:34:56,123Z') # no …
```

READY FOR REVIEW - Fix #219. Add minimal support for fractional seconds longer than six digits.

---

arrow/locales.py

```
just now        éppen most
in seconds      pár másodperc múlva
in a minute     egy perc múlva
in 4 minutes    4 perc múlva
in 29 minutes   29 perc múlva
in an hour      egy óra múlva
in 2 hours      2 óra múlva
in a day        egy nap múlva
in 2 days       2 nap múlva
in 6 days       6 nap múlva
in 13 days      13 nap múlva
in a month      egy hónap múlva
in 2 months     2 hónap múlva
in a year       egy év múlva
in 2 years      2 év múlva
just now        éppen most
seconds ago     másodpercekkel ezelőtt
a minute ago    egy perccel ezelőtt
5 minutes ago   5 perccel ezelőtt
30 minutes ago  30 perccel ezelőtt
an hour ago     egy órával ezelőtt
2 hours ago     2 órával ezelőtt
a day ago       egy nappal ezelőtt
2 days ago      2 nappal ezelőtt
7 days ago      7 nappal ezelőtt
14 days ago …
```

Hungarian translation

---

arrow/arrow.py
tests/arrow_tests.py

I found the problem in `span_range` function:
```python
In [5]: arrow.Arrow.span_range('week', arrow.Arrow(2014, 9, 10), arrow.Arrow(2014, 9, 16))
Out[5]: 
[(<Arrow [2014-09-08T00:00:00+00:00]>,
<Arrow [2014-09-14T23:59:59.999999+00:00]>)]
```
but if I shift start_date early, I get the extra week:
```python
In [6]: arrow.Arrow.span_range('week', arrow.Arrow(2014, 9, 9), arrow.Arrow(2014, 9, 16))
Out[6]: 
[(<Arrow [2014-09-08T00:00:00+00:00]>,
<Arrow [2014-09-14T23:59:59.999999+00:00]>),
(<Arrow [2014-09-15T00:00:00+00:00]>,
<Arrow [2014-09-21T23:59:59.999999+00:00]>)]
```
The second behavior, I think, correct: all tests of other time frames include period with end date. So I correct the `span_range` test for week (add absent period) and fix the behavior of `span_range` to pass it.

fix span_range stability

---

arrow/factory.py
tests/factory_tests.py

It now can support (str, format, tzinfo=tzinfo())
```
In [1]: import arrow
In [2]: from dateutil import tz
In [3]: timefmt = 'YYYYMMDD HH:mm:ss.SSS'
In [4]: d = '20150514 03:08:22.992'
In [5]: arrow.get(d, timefmt)
Out[5]: <Arrow [2015-05-14T03:08:22.992000+00:00]>
In [6]: arrow.get(d, timefmt, tzinfo=tz.tzlocal())
Out[6]: <Arrow [2015-05-14T03:08:22.992000+08:00]>
```

Modify tzinfo parameter in `get` api,

---

arrow/arrow.py
arrow/locales.py
tests/arrow_tests.py

adds a param for humanized duration without "in" and "ago" prefix/suffix, maybe for things like "you been running for 8 minutes"

humanize for time duration

---

arrow/parser.py
docs/index.rst
tests/parser_tests.py

Unknown tokens in the string are ignored.
In the previous implementation, each token was matched individually.
With the format 'YYYY-MM-DD', parsing the string '2000 ... 2015-12-31'
would fail because 'YYYY' taken alone matches the first 4 numbers.
Same with the format 'MMMM YYYY' and the string 'June was born in May
1980'. 'MMMM' would match 'June' instead of 'May' even if there are no
digits next to it.
This change builds a complete pattern string by replacing each token by
its pattern. 'YYYY-MM-DD' becomes '(?P<YYYY>\d{4})-(?P<MM>\d{2})-(?P<DD>\d{2})'.
The search is done with that string.
That matches '2015-12-31' in the previous example.

Search date in strings

---

arrow/arrow.py
tests/arrow_tests.py

Here's what used to happen:
```py
arrow.utcnow() + None #=> raises NotImplementedError()
```
Now: 
```py
arrow.utcnow() + None #=> raises TypeError()
```
Fixes #241.
I'm not sure this is actually what should be happening but I already wrote it when I read that TypeError should not be raised.

Raise TypeError when adding/subtracting non-dates

---

arrow/arrow.py

I have an issue to report and not sure if it is related #154 .
I have the issue that `arrow.to()` return wrong offset as well.
According to [pytz's README](http://bazaar.launchpad.net/~stub/pytz/devel/view/head:/src/README.txt), caller should call `zone_instance.localize()` instead of just passing zone_instance to standard python datetime.
From arrow.to()'s internal implementation, we should assign new arrow instance with astimezone() returned timezone which is correct from zone.localize().
Tested with #154 's case: ( arrow==0.5.4 , pytz==2015.4 )
```
In [1]: import arrow
In [2]: import pytz
In [3]: str(arrow.utcnow().to(pytz.timezone("America/Los_Angeles")).datetime)
Out[3]: '2015-08-03 03:00:50.856870-07:00'
In [4]: str(arrow.utcnow().to(pytz.timezone("America/Los_Angeles")))
Out[4]: …
```

Fix pytz conversion error

---

docs/index.rst

Note that arrow's tokens differ from strptime's.

---

arrow/arrow.py
tests/arrow_tests.py

In the recently released arrow 0.6.0, the ``span_range`` method now returns superfluous ranges.
The lower bound gets artificially rounded to the day granularity:
```python
$ python
Python 2.7.10 (default, Jun 10 2015, 19:42:47) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
>>> arrow.__version__
'0.6.0'
>>> now = arrow.utcnow()
>>> now
<Arrow [2015-07-20T12:38:22.561417+00:00]>
>>> arrow.Arrow.span_range('hour', now, now)
[(<Arrow [2015-07-20T00:00:00+00:00]>,
<Arrow [2015-07-20T00:59:59.999999+00:00]>),
(<Arrow [2015-07-20T01:00:00+00:00]>,
<Arrow [2015-07-20T01:59:59.999999+00:00]>),
(<Arrow [2015-07-20T02:00:00+00:00]>,
<Arrow [2015-07-20T02:59:59.999999+00:00]>),
(<Arrow [2015-07-20T03:00:00+00:00]>,
<Arrow [2015-07-20T03:59:59.999999+00:00]>), …
```

Fix overzealous time truncation in span_range()

---

arrow/parser.py
tests/parser_tests.py

Hi!
So, I've added more separators (`- / .`) for parsing to fix #174.
Additionally, I've added tests for them, as per #242.
Cheers!

Extend parseable formats

---

arrow/parser.py
docs/index.rst
tests/parser_tests.py

Solution proposed as a fix to issue #275  
* try to test various available tz naming conventions
* rename existing `test_parse_tz` to `test_parse_tz_zz` in order
to separate ZZ tests from ZZZ
* update token table in docs
* add new regex for ZZZ token and leverage existing code that recognizes
timezones via dateutil
This does not include improvements (refactoring) to existing code proposed also in the issue thread.

parser: add new ZZZ token to recognize/parse TZ names from the tz database

---

arrow/locales.py

These languages use periods (baseline dots) as ordinal indicators.

Add ordinal indicators for German & Finnish

---

arrow/locales.py
arrow/parser.py

In most European languages, the names of days and months are not capitalized (with German being a notable exception).
The first commit in this PR fixes said capitalization for a number of languages. Catalan is also affected, but I didn't touch it so as not to create a conflict with #257.
Some tests started failing, and it turned out that the month-name-to-ordinal lookup logic had a bug. The keys in `locale._month_name_to_ordinal` were in their raw forms, while lookups were always performed based on a capitalized value. Consequently, the lookups would only work for locales where the names had been specified with an uppercase initial.
The second commit fixes this by standardizing the lookup dictionary to all-lowercase keys.

Fix month ordinal lookups and locale capitalizations

---

arrow/arrow.py
tests/arrow_tests.py

Fix #263: provide missing format calls for exception messages

---

.gitignore
tests/arrow_tests.py

Just a patch of `arrow_tests.py` to fix the Python 3 errors and added some general `.gitignore` file patterns for `vim` and `patch`.
The error was introduced in pull request #264.

Fix test errors caused by `Exception.message` which is removed since Python 3.0.

---

.coveragerc
.travis.yml
Makefile
README.rst
arrow/locales.py
setup.cfg
tests/arrow_tests.py
tests/factory_tests.py
tests/formatter_tests.py
tests/locales_tests.py
tests/parser_tests.py

With codecov we can see current coverage status easily.
Also replace pypip badges with shield.io (badges/pypipins#37) since the badge hosting at 'pypip.in' has been broken for a while now.

Add codecov support and enforce coverage tests

---

arrow/parser.py
tests/parser_tests.py

It is currently impossible to parse dates which contain data matching an internal pattern used by arrow.
For example, `Thursday, December 10, 2015 at 5:09pm -0700`. A format string for arrow to parse this would be, `MMMM D, YYYY at h:mma Z`.
Unfortunately, this doesn't work because the `a` in `at` gets interpreted as the marker for am/pm parsing in accordance with the documentation [here](http://crsmithdev.com/arrow/#tokens).
This pull request offers a workaround by escaping anything that is square bracketed within a format and interpreting it as only text.
This fixes the above pattern: `MMMM D, YYYY [at] h:mma Z`
Arrow can now successfully parse the expression:
```python
>>> DATE_FORMAT = "MMMM D, YYYY [at] h:mma Z"
>>> my_date = "Thursday, December 10, 2015 at 5:09pm …
```

Added support for escaping within parsing formats

---

arrow/arrow.py
tests/arrow_tests.py

While I saw quarters used in `range` and `span_range`, I didn't see a way to have an instance property, e.g.
```python
a = arrow.utcnow()
print(a.quarter) # 1,2,3, or 4
```

adding arrow.quarter property and relative `replace` options

---

docs/index.rst

Perhaps the name changed along the way or it was a typo thinking of the fully qualified class name `arrow.factory.ArrowFactory`.

Fix typo in docs for using arrow.ArrowFactory

---

arrow/arrow.py
tests/arrow_tests.py

Fixes https://github.com/crsmithdev/arrow/issues/301
The correct implementation of magic methods should return NotImplemented rather than raising a TypeError. I kept it this way to be consistent with other methods.
Same applies to tests: they should use arithmetic operators, rather than calling the magic methods directly. Again, I'm keeping consistency with existing tests.
I can submit another PR to address these issues.

fixed #301: __rsub__ returns timedelta of opposite sign

---

arrow/locales.py

- "秒" into "数秒"
- It will be "秒前" and "秒後" after it has be concatenated.
- It doesn't make sense (smattering).

Update Japanese local

---

arrow/arrow.py
arrow/locales.py
tests/arrow_tests.py
tests/locales_tests.py

It appears the newest build is broken due to problems with the Romansh locale. There are also test coverage issues with the EsperantoLocale (incorrect testing done), and the BulgarianLocale tests accidentally use the RussianLocale as the testing base.
This pull request fixes all of those.
Whoever is merging these should be more vigilant.

Fixed problems with coverage, broken build, and testing

---

arrow/arrow.py

Added error description at AttributeError on invalid `Arrow.replace` key.
When passing an invalid key to `Arrow.replace`, the invalid key is included in the message:
>>> arrow.now().replace(foo: 42)
AttributeError: unknown attribute: "foo"

included error message

---

arrow/locales.py
tests/locales_tests.py
tests/parser_tests.py

According to Wikipedia: [](https://en.wikipedia.org/wiki/Ordinal_indicator#.C2.BA_and_.C2.AA)
> In Italian, Spanish, Galician and Portuguese, the suffixes º and ª are appended to the numeral depending on whether the grammatical gender is masculine or feminine respectively. º is not to be confused with the superscript lower-case o (o), the degree symbol (°), or the ring diacritic (˚); ª is not to be confused with the superscript lower-case a (a).
Before this fix, the character for masculine was incorrect and feminine was missing at all

Ordinal pattern fix for Italian & Spanish

---

arrow/locales.py

I had two improvements about Korean Locale.
1. "몇초" to "몇 초": See [Rules of Korean spelling (Section 43)](http://www.korean.go.kr/front/page/pageView.do?page_id=P000074) (Korean). It says noun that expressing unit should leave space.
2. "일 분" to "1분": Keep consistency with below `'minutes'`.

Update Korean Locale

---

README.rst
docs/index.rst

Based on `setup.py`, versions 3.4 and 3.5 are also supported; update docs to reflect that.

Fix supported Python versions in documentation

---

setup.cfg

Since arrow is a pure python module which support python 2 and 3 with the same code, it can be put in a universal wheel.

Add support for universal wheels

---

arrow/util.py
tests/factory_tests.py

Before:
```
>>> arrow.get(False)
<Arrow [1970-01-01T00:00:00+00:00]>
>>> arrow.get(True)
<Arrow [1970-01-01T00:00:01+00:00]>
```
After:
```
>>> arrow.get(False)
TypeError: Can't parse single argument type of '<type 'bool'>'
>>> arrow.get(True)
TypeError: Can't parse single argument type of '<type 'bool'>'
```
Closes #238.

Throw TypeError when passing booleans to arrow.get

---

arrow/locales.py
tests/locales_tests.py

This enables 'de_ch'. It's another class even though it's the exact same as 'de_de' and 'de_at'. But if there's every anything else that needs to be added in the future there is a good chance that they will diverge. So personally I think breaking DRY here is reasonable.
I also added what is basically a smoke test.

Add SwissGerman localization

---

arrow/arrow.py
tests/arrow_tests.py

This resolves the merge conflicts from https://github.com/crsmithdev/arrow/pull/276.  It also fixes (in https://github.com/crsmithdev/arrow/pull/349/commits/b5eee6ddf91f6479309a8597f3052a0f8ffa37a0) a bug in the `quarters` functionality, adds `quarters` to `shift`, and gets back to 100% code coverage.
Separating replace and shift functionality would save a lot of headaches!

Separate replace & shift function

---

.coveragerc
arrow/api.py
arrow/arrow.py
arrow/locales.py
arrow/parser.py
docs/conf.py
docs/index.rst
setup.cfg
tests/arrow_tests.py
tests/factory_tests.py
tests/parser_tests.py
tests/util_tests.py

There's two things that arrow isn't doing quite right with respect to fractional seconds:
1. The separator is sometimes comma. In fact, this is the "preferred" separator per the standard.
2. The fractional seconds have arbitrary precision; the only requirement is that the sender and receiver agree on the precision. For example, a high-energy physics lab might use iso-8601 timestamps with attosecond precision without violating the standard.
I've left a couple TODO's below, on which I'd like to get your input. I had to make a couple compromises when implementing this:
1. Python's stdlib datetime only accepts microseconds, so any fractional seconds of higher precision have some data loss, but are parsed as accurately as possible. 
2. In "fixing" the date-format code, I made any number of S …

Support gnu date iso 8601

---

arrow/arrow.py
tests/arrow_tests.py

I was reading the docs and I think this was the intended behaviour. If this is alright, I'll add some tests.

respect limit even if end is defined in a range

---

arrow/formatter.py
tests/arrow_tests.py

Specifying ZZ in a format string gives an offest of -00:00 for UTC,
despite the arrow object repr showing +00:00. Detect `using >= 0`
for consistency.

Fix negative offset for UTC

---

arrow/arrow.py
tests/arrow_tests.py

Fixes issue https://github.com/crsmithdev/arrow/issues/378
I added test cases for quarter end dates to make sure they were being included in the correct quarter (as well as a fix).

Fixes #378: __getattr__ has an off-by-one error in its quarter handling

---

arrow/parser.py
requirements.txt
tests/parser_tests.py

This PR improves the performance of `arrow.parser.DateTimeParser` by caching compiled regular expressions in an LRU cache of configurable size. By default, it is set to 0 (disabled).
This cuts parsing speed by approximately two thirds, which can be significant when parsing very large data sets.
```python
In [1]: import timeit
...: 
...: setup = """\
...: from arrow.parser import DateTimeParser
...: 
...: parser = DateTimeParser('en_us', cache_size=%s)
...: format = "dddd, MMMM D, YYYY [at] h:mmA"
...: string = "Friday, December 14, 2015 at 1:03pm PDT"
...: """
...: 
...: test_function = "parser.parse(string, format)"
...: 
...: without_cache = timeit.timeit(stmt=test_function, setup=setup % 0, number=1000000)
...: print("Time to process without cache: %s" % without_cache)
...: 
...: …
```

Cached compiled format strings to speed up repetitive parsing

---

arrow/arrow.py
tests/arrow_tests.py

https://github.com/crsmithdev/arrow/issues/362
From the issue above, implemented an interval function that takes in frame, start, end, tz, and also interval value to give interval on specific time range. (i.e. : frame = 'hour' with interval =2 will give tuples with 2 hour difference within the range)

implementation of interval function

---

arrow/arrow.py

Previously:
arrow.Arrow.fromtimestamp(0, pytz.timezone('Europe/Paris'))
Now:
arrow.Arrow.fromtimestamp(0, pytz.timezone('Europe/Paris'))

Fix for poperly handle tz passed in from pytz

---

arrow/arrow.py
arrow/locales.py
tests/arrow_tests.py

New feature allowing to select the granularity of the humanize function. We can receive for example 65 minutes ago rather than 1 hour ago.

Humanizegranularity

---

arrow/arrow.py
docs/index.rst

Commit 15d903a (from #349), separated the replace and shift features
into two functions.  However the docs still show the old, deprecated and
more confusing use of replace to shift the time.

Replace ".replace" with new ".shift" function in docs

---

arrow/locales.py

According to this [German SE answer](http://german.stackexchange.com/a/34107/25165) the special case for `timeframes['days']` in `AustriaLocale` is wrong.

Remove `timeframes['days']` handling from `AustriaLocale`

---

arrow/arrow.py

This is a pretty minor change, I just goofed it up and was a bit confounded by the non-descriptive error message. This should make it clearer what happened.

Added more human-readable error message for invalid frames for range/span

---

arrow/factory.py

Currently, the kwargs `locale` and `tzinfo` to `arrow.get` are undocumented. I was about to contribute code to allow timezone specification when parsing with `arrow.get`, e.g.,
```py
arrow.get('01-01 00:00', 'MM-DD HH:mm')
```
when I realized the technology has already been there:
```py
arrow.get('01-01 00:00', 'MM-DD HH:mm', tzinfo='America/New_York')
```
since #221. Therefore, I believe the documentation could be improved to expose this useful feature to more users.

ArrowFactory.get: document kwargs locale and tzinfo

---

arrow/locales.py

This fixes a minor grammar mistake in `BrazilianPortuguese` locale, past should not be `fazem` but `faz`.

Fixes minor in PortugueseBrazilian locale

---

setup.py

https://github.com/crsmithdev/arrow/issues/495
This PR dynamically adds `'backports.functools_lru_cache==1.2.1'` to `install_requires` if python version is less than `3`.
This is urgent cause `arrow` is broken in `py2.x` versions.

Add functools-lru-cache to setup

---

.gitignore
setup.py

This allows universal wheels to be generated and reliably installed.
Version 0.11 (of **arrow**) introduced caching, but based on a feature that was added to the Python standard library post-2.7. This meant that *arrow* became un-usable with Python 2.7.
Version 0.12 was released to fix the above problem. It did this by adding the [following code to setup.py](https://github.com/crsmithdev/arrow/blob/66ac19380931e9bc0497aa5ecd0f34632f4e06cd/setup.py#L29-L31):
```py
install_requires = ['python-dateutil']
if sys.version_info[0] < 3:
install_requires.append('backports.functools_lru_cache==1.2.1')
```
This code declares the required dependency, but requires code to run on install to do so. Wheels *do not run code at install time*, rather *code is run on wheel generation*. This meant that …

Allow wheels to determine the required dependencies

---

arrow/locales.py
tests/locales_tests.py

Tagalog ordinal number formatting taken from _Manwal sa Masinop na Pagsulat_ p.78. I closed a [previous PR](https://github.com/crsmithdev/arrow/pull/469) I made related to this as I overlooked the already existing TagalogLocale.

Tagalog locale additions

---

arrow/arrow.py

This fixes #477. `datetime.utcnow()` is an abomination that returns a *naive* datetime representing the current time in UTC. It is very rarely what you want. Since `arrow` is returning aware datetimes from both of these operations, `datetime.now(the_desired_zone)` is preferable.

Drop datetime.utcnow in favor of datetime.now(UTC)

---

arrow/api.py

Have taken the good documentation found in `arrow.factory.ArrowFactory` for the `get`, `now` and `utcnow` methods and replaced the somewhat lacking documentation for the wrappers in `arrow.api`. Now, IDEs and REPLs will produce the better documentation when asked to.

get, now & utcnow will now use docs found in ArrowFactory

---

.gitignore
arrow/arrow.py
arrow/util.py
tests/arrow_tests.py

Based off of @rominf's PR https://github.com/crsmithdev/arrow/pull/440, implementing https://github.com/crsmithdev/arrow/issues/251, and using an idea from @pganssle.

Return generator instead of list in Arrow.range() et al

---

arrow/factory.py
tests/factory_tests.py

Allow arrow.get() to be called with str+tzinfo parameter combo.
Before this fix:
```
In: arrow.get('2018-01-29 14:46', tzinfo=tz.timezone('US/Central'))
Out: <Arrow [2018-01-29T14:46:00+00:00]>
```
After:
```
In: arrow.get('2018-01-29 14:46', tzinfo=tz.gettz('US/Pacific'))
Out: <Arrow [2018-01-29T14:46:00-08:00]>
```
Fixes #515, #462, and #493.

Fix arrow.get() to work with str+tzinfo

---

arrow/arrow.py

I was fixing some deprecation warnings in code I use, and came across this formatting error.  (reads "valueis")

Fix spacing in deprecation warning

---

arrow/locales.py
tests/locales_tests.py

When using the `humanize` method of arrow lib with the "only_distance" option set to true, in german language there are some special cases which have to be translated different than if not using the option.
For example "in one hour" in german is "in einer Stunde", with "only_distance" set to true, it is "one hour" which is translated to "einer Stunde" at the moment. But it would be better to translate it like "eine Stunde".
This PR adds these special cases to the german localisation.

Add additional timeframes translations for german language

---

arrow/arrow.py
tests/arrow_tests.py

After doing a little bit of debugging I found that the floating point delta value was being truncated by a cast to an int. If we simply round the number before casting this fixed the issue mentioned in https://github.com/crsmithdev/arrow/issues/541.
I have also included the test cases described in the issue thread.
Closes: #541

Fix humanize behavior with future days

---

README.rst
setup.py

I added a couple of badges to the README to show the currently supported Python versions along with the license. I also added a couple of missed references to the new support for Python 3.8.

Added badges and updated README

---

arrow/__init__.py
setup.py

I noticed `setup.py` was using some outdated Python methods that were most likely used to support `Python 2.6` and lower, but since `arrow` only support >=2.7, I think it is appropriate to cleanup setup.py to deprecate distutils and replace `fpath` and `codecs` with modern `open` syntax.
You can test this change with the following commands:
`make clean && make build27 && . local/bin/activate && python setup.py test`
`make clean && make build37 && . local/bin/activate && python setup.py test`

Cleaned up and updated setup.py

---

HISTORY.md
arrow/__init__.py
setup.py

@systemcatch @crsmithdev we need to get this patch pushed ASAP since a recent change broke the install.
Fixes: https://github.com/crsmithdev/arrow/issues/598
This other PR I am working on should prevent such as issue from coming up in the future: https://github.com/crsmithdev/arrow/pull/597

Fixed regression from 0.14.0

---

setup.py

This is another regression in 0.14.0
Fixes: https://github.com/crsmithdev/arrow/issues/600

Always open README with utf-8 encoding

---

.pre-commit-config.yaml
.travis.yml
HISTORY.md
Makefile
arrow/__init__.py
setup.cfg
setup.py
tox.ini

Along with these tox configuration changes, I also updated the `isort` config to not conflict with Black (which wraps import lines beyond 88 characters and uses trailing commas).
Closes: https://github.com/crsmithdev/arrow/issues/589

Updated tox file and changed Travis CI to use tox

---

.gitignore
Makefile

In order to help with debugging Arrow, I started to use JetBrain's pycharms alongside vscode. But it creates a ton of configuration files and folders that I needed to add to the gitignore.
Because of this, I took the liberty to add to the gitignore a number of templates from https://github.com/github/gitignore, including the python, vscode, jetbrains, and OS templates.
Furthermore, I took the time to change the name of the virtual env created in the makefile from `local` to `venv` to better conform to common standards and style.

Updated name of virtualenv from local to venv and updated gitignore

---

README.rst

The Travis CI build is currently shown as failing because the badge is not set to point to the master branch builds, but rather all Travis builds. Since we are working on some fixes in other branches that are currently failing, it is best to point the badge to the latest passing master Travis build. I also adjusted the orderings of the targets in the `README.rst` file.

Fixed README to point to Travis master build

---

.travis.yml

Since Python 3.8 is now in beta, I think it is appropriate to remove it from `allow_failures`.

Official Python 3.8 support

---

arrow/locales.py
tests/parser_tests.py

```shell
arrow.get('Junio 30, 2019 - 08:00 pm', "MMMM DD, YYYY - hh:mm a", locale="es")
<Arrow [2019-06-30T20:00:00+00:00]>
```
/cc @NestorTejero
ref #607

Add meridians to Spanish locale

---

arrow/factory.py
tests/factory_tests.py

@jadchaar this is the small snippet of code I showed you a while back on zoom.
Essentially this lets us handle kwargs properly like the Arrow() constructor already does without having to do a ton of refactoring. Let me know if you think it's worth using as a quick fix.
```shell
arrow.get(year=2016, month=7, day=14)
<Arrow [2016-07-14T00:00:00+00:00]>
``` 
ref #415

Allow factory.get() to construct with kwargs

---

docs/index.rst
requirements.txt

I also removed the version locks from `requirements.txt` to force the latest versions of the packages to be installed.
Related to the discussion here: https://github.com/crsmithdev/arrow/issues/35

Added escaping to docs

---

arrow/factory.py
tests/factory_tests.py

In v 0.14.2 passing a date string, a format string and tzinfo kwarg where the value is a string worked correctly. This usage pattern broke in 0.14.3. This restores the previous behavior.

Fix regression when tzinfo kwarg is a string

---

setup.py

This is now the official method for conditionally requiring python versions as documented here: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies. Pytest does the same here: https://github.com/pytest-dev/pytest/blob/master/setup.py#L11.
Addresses: https://github.com/crsmithdev/arrow/issues/495

Move backports from extra_requires to install_requires

---

arrow/arrow.py
tests/arrow_tests.py

I am going through some of the issues mentioned in [this blog post from 2016](https://blog.eustace.io/please-stop-using-arrow.html) and I think it is time that we finally remove the ability to shift from the `replace` function in arrow. A deprecation warning has been in place since 2016, so I think it is an appropriate time to remove this functionality.

Removed deprecated replace shift functionality

---

HISTORY.md

I added a bit more context to the history file to better describe the deprecation pushed in `v0.15.0`.

Updated HISTORY to reflect deprecation changes

---

README.rst

@catwell pointed out that we still have some references to the deprecated replace functionality with plural properties in the docs. I could only find one instance in the docs, but I made sure to replace it with `shift`.

Removed instances of replace with plural properties from docs

---

arrow/parser.py
tests/parser_tests.py

Fixes https://github.com/crsmithdev/arrow/issues/636

Handle date with over 999999 microseconds

---

arrow/locales.py

Following [release 0.14.6](https://github.com/crsmithdev/arrow/releases/tag/0.14.6), here the French translations for week/weeks.

Add French locale for week granularity

---

arrow/parser.py
tests/parser_tests.py

This solves https://github.com/crsmithdev/arrow/issues/662
Currently arrow does not allow you to pass in negative numbers for seconds relative to epoch when using strings. This patch is an attempt to fix this.

0.15.0 regression - Support negative numbers in the timestamp regular expression

---

arrow/arrow.py
requirements.txt
setup.cfg
tests/factory_tests.py
tests/parser_tests.py

Closes: https://github.com/crsmithdev/arrow/issues/658

Fix bug with tzinfo.zone check in factory.get

---

arrow/arrow.py
arrow/factory.py
arrow/util.py
tests/arrow_tests.py
tests/factory_tests.py
tests/util_tests.py

The previous implementation of `is_timestamp` was a bit clunky and inefficient, so I refactored it to improve efficiency. I also changed `Arrow.fromtimestamp` and `Arrow.utcfromtimestamp` to use this revamped `is_timestamp` function.
This is in preparation from my next PR which will implement the "x" timestamp token.

Refactored timestamp methods and optimized is_timestamp

---

CHANGELOG.rst
README.rst
arrow/arrow.py
arrow/factory.py
arrow/parser.py
docs/index.rst

Source: https://en.wikipedia.org/wiki/ISO_8601

Renamed ISO-8601 to ISO 8601 in docs to conform with Wikipedia page

---

tests/parser_tests.py

Zones are retrieved via [dateutil](https://dateutil.readthedocs.io/en/stable/zoneinfo.html?highlight=zoneinfofile#dateutil.zoneinfo.get_zonefile_instance) (though `ZoneFileInfo.zones` is not documented), and [pytz](http://pytz.sourceforge.net/#helpers) and are used in existing test `tests.parser_tests:DateTimeParserParseTests.test_parse_tz_name_zzz`.
Closes: crsmithdev/arrow#657

Test TzinfoParser against full timezone database

---

arrow/locales.py

```ValueError: Humanization of the 'weeks' granularity is not currently translated in the 'vi_vn' locale. Please consider making a contribution to this locale.```

add "week" translation for vi-vn locale

---

arrow/formatter.py
arrow/parser.py
tests/formatter_tests.py

`"BRST"` was never going to work in this test so I've substituted `"CST"` for now, this is a minor fix until we can test fully against the tz database.
closes #554

Update formatter tests for tz abbreviations

---

tests/formatter_tests.py
tests/parser_tests.py
tests/utils.py

Closes #693 
Similar to #657, zones are retrieved via dateutil and pytz, and are used in existing test. The abbreviation is also retrieved from the existing test, using the method `tzname()`.

Test formatter against full timezone database #693

---

arrow/__init__.py

Adding ParserError to the module exports allows users to easily catch that specific error. It also eases lookup of that error for tools like PyCharm.

Add ParserError to the module exports.

---

arrow/parser.py
tests/parser_tests.py

Add support for midnight at the end of day

---

arrow/arrow.py
tests/arrow_tests.py

The parameter allows to specify whether returned intervals should be closed, open, left-open or right-open. The parameter values and their semantics are identical to existing Arrow.in_between method.
Closes #687

Added bounds parameter to Arrow.span_range, Arrow.interval and Arrow.span (#687)

---

arrow/arrow.py
arrow/parser.py
arrow/util.py
tests/parser_tests.py
tests/util_tests.py

Adds support for negative timestamps on Windows by computing the `datetime` directly using `timedelta`.  This is method is only used as a fallback, so on other platforms or with positive timestamps the `datetime.fromtimestamp` or `datetime.utcfromtimestamp` methods are used.
Closes #675

Add support for negative timestamps on Windows (#675)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

I got inspiration from https://github.com/psf/requests/issues/new/choose to add PR and issue templates. This will ease the process of triaging bugs and will improve PR and issue quality.
Will allow us to get more details about bugs and PRs up front rather than probing in extra follow ups.
We may have to talk to Chris about enabling the issue templates through settings, but I think they should work automatically since the folder and PR template naming is special.

Added PR and issue templates

---

arrow/parser.py
docs/index.rst
tests/factory_tests.py
tests/parser_tests.py

This should fix #701. I decided to allow the punctuation: `` , . ; : ? ! " ' ` [ ] { } ( ) < > ``.

Improve parsing of local strings with punctuation

---

arrow/factory.py
tests/factory_tests.py

First attempt at this as discussed, not sure about this behaviour though. Any thoughts @jadchaar ?
```shell
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
>>> arrow.get(1367900664)
<Arrow [2013-05-07T04:24:24+00:00]>
>>> arrow.get(1367900664).replace(tzinfo="US/Pacific")
<Arrow [2013-05-07T04:24:24-07:00]>
>>> from dateutil import tz
>>> time_zone = tz.gettz('US/Pacific')
>>> arrow.get(1367900664, tzinfo=time_zone)
<Arrow [2013-05-06T21:24:24-07:00]>
```

Allow factory.get() to construct from a timestamp and timezone

---

arrow/arrow.py
arrow/parser.py
arrow/util.py
tests/parser_tests.py
tests/util_tests.py

Reverts #700 entirely due to https://github.com/crsmithdev/arrow/blob/master/tests/util_tests.py#L58 causing intermittent test (and hence build) failures. There is also some debate whether the feature is actually returning correct answers due to DST causing problems.
ref #675 
/cc @kkoziara

Revert support for negative timestamps on Windows

---

arrow/formatter.py
arrow/parser.py
docs/index.rst
tests/test_formatter.py
tests/test_parser.py

This adds support for ISO 8601 [week dates](https://en.wikipedia.org/wiki/ISO_week_date) via a new token `"W"`.
```shell
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
>>> arrow.get("2013-W29-6", "W")
<Arrow [2013-07-20T00:00:00+00:00]>
>>> arrow.get("2013-W12", "W")
<Arrow [2013-03-18T00:00:00+00:00]>
>>> arrow.get("2013W296", "W")
<Arrow …
```

Add support for parsing and formatting ISO 8601 week dates

---

arrow/formatter.py
tests/test_formatter.py

There's a failing test which we need to discuss, otherwise this is working ok.
```shell
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
>>> adt=arrow.utcnow()
>>> adt.format("x")
'1585669870688329'
>>> adt.format("X")
'1585669870'
```

Allow formatting with 'x' token

---

arrow/locales.py
tests/test_locales.py

(:x: No documentation change needed.)
I've added missing `week` and `weeks` timeframes to Polish locale and also fixed the grammar errors in the existing entries.

Add week timeframe to Polish locale

---

arrow/locales.py
tests/test_locales.py

German locales are missing translations for the week/weeks granularities.
While working on that, I noticed that `SwissLocale` has them and that it declared itself responsible for plain `de` (as well as `GermanLocale`), so it's a question of chance which one is used to localize for `de` (as opposed to `de_de` or `de_ch`). As I couldn't spot an effective difference between the two, this PR merges both into one class (for `de`, `de_ch`, `de_de`). Additionally, I renamed `DeutschBaseLocale` to `GermanBaseLocale` for consistency and, because its purpose wasn't clear to me right away, straightened out the custom `describe()` method.
/cc @href You might want to take a look at this, please check if I missed anything regarding the equivalence of `GermanLocale` and `SwissLocale`.
Thank you for …

Consolidate German locales and add missing 'week'/'weeks' localization

---

setup.cfg
tests/test_factory.py

This PR makes the dateparser tests skipped if dateparser is not installed. This would help us since we don't have it packaged and don't want yet another package to maintain for one test.

Skip dateparser tests when the package is not installed

---

MANIFEST.in
Makefile
setup.cfg
tox.ini

Also, I moved configuration settings from setup.cfg to tox.ini.
Closes: https://github.com/crsmithdev/arrow/issues/783

Package tox and dependencies in distribution tarball

---

arrow/locales.py
tests/test_locales.py

This PR fixes the Portuguese locales values. They should essentially be the same as the Brasilian ones. Also fixed capitalization. We use month name with caps in Portugal.
Thanks.

Fix Portuguese locale capitalization

---

.github/workflows/continuous_integration.yml
.travis.yml
Makefile
README.rst
setup.py
tox.ini

Adds support for Python 3.9 and pypy3 in `tox.ini`, `Makefile`, and Travis CI.
Github actions does not support development versions yet, but it is an open issue here: https://github.com/actions/setup-python/issues/20.

Add Python 3.9 support

---

tests/test_arrow.py

We get very intermittent failures on our tests due to https://github.com/crsmithdev/arrow/blob/master/tests/test_arrow.py#L1539, this is my attempt to fix this.
The basic idea is that `humanize` will use `now` in whatever time zone the object calling it is in. Since `now` is always moving the result will change over time e.g.
```shell
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for …
```

Fix intermittent regression test failure

---

arrow/arrow.py
tests/test_arrow.py

Adding a deprecation warning for Python 2.7 and <=3.5.

Adding a deprecation warning for Python 2.7 and <=3.5.

---

arrow/arrow.py
tests/test_arrow.py

closes #72 
Pendulum example is now fixed.
```shell
Python 3.8.3 (default, Jul  7 2020, 18:57:36) 
[GCC 9.3.0] on linux
>>> just_before = arrow.get(2013, 3, 31, 1, 55, "Europe/Paris")
>>> just_before = arrow.get(2013, 3, 31, 1, 55, tzinfo= "Europe/Paris")
>>> just_before
<Arrow [2013-03-31T01:55:00+01:00]>
>>> just_before.shift(minutes=+10)
<Arrow [2013-03-31T03:05:00+02:00]> …
```

Improve handling of imaginary datetimes

---

arrow/arrow.py
tests/test_arrow.py

This is the start of implementing #465 
- New property `int_timestamp` that does exactly the same thing as `.timestamp`.
- `timestamp` will be removed in 1.0.0
- I have not touched `float_timestamp` in this PR.
- `float_timestamp` essentially does the same as `datetime.timestamp()`, we could leave it as a legacy property.

Add new int_timestamp property in preparation for 1.0.0 release

---

arrow/arrow.py
arrow/util.py
tests/test_arrow.py

Thanks for the library. This PR provides a fix for #842

Fix range behaviour at end of month/quarter/year frames (#842)

---

arrow/locales.py

Fixes:
```
(arrow.get() - timedelta(seconds=33)).humanize(locale="fr")
'il y a 33 quelques secondes'
```
Either say "a few seconds ago": "il y a quelques secondes" or "33 seconds ago": "il y a 33 secondes", not "a few 33 seconds ago"

Fix french locale

---

tox.ini

Removes lint and docs targets from the tox envlist. This will allow folks to run all tests on the distribution tarball using tox with a simple `tox` command. Our linting suite requires pre-commit, which fails outside of a git repository, so it is probably best to leave out the linting related targets and instead invoke them manually via `tox -e lint` and `tox -e docs`.
Closes: https://github.com/arrow-py/arrow/issues/864
Closes: https://github.com/arrow-py/arrow/issues/869

Remove lint and docs targets from tox envlist

---

arrow/arrow.py
tests/test_arrow.py

Merged PR #817 with updated master. Added edge cases in span_range function when exact keyword is True. Added correlated tests for span_range. 
Closes: #498

Add 'exact' keyword in span_range, span and interval methods 

---

arrow/locales.py

There is a small typo in arrow/locales.py.
Should read `input` rather than `inpute`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

Fix simple docs typo, inpute -> input

---

arrow/arrow.py
tests/test_arrow.py

Removing the `tzinfo.setter` to help with hashing and consistency.
```shell
Python 3.8.3 (default, Jul  7 2020, 18:57:36) 
[GCC 9.3.0] on linux
>>> from dateutil import tz
>>> dt=arrow.utcnow()
>>> dt.tzinfo=tz.gettz("US/Pacific")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
>>> …
```

Remove tzinfo.setter and update tests

---

arrow/locales.py

Removed a word that was left over from a previous refactoring. By mistake, somebody had changed `noen sekunder` to  `{0} noen sekunder` (lit. translated: `some seconds` -> `{0} some seconds`).
Also corrected some of the Norwegian strings, e.g. "et" -> "ett" (lit. translated: "a" -> "one"), for both variants.

Correct Norwegian grammar

---

setup.py

Add `py.typed` file and export type annotations per [PEP 561](https://www.python.org/dev/peps/pep-0561/) so that type testing tools like mypy can actually verify types when using arrow.
No new test added for this change and I don't think there's any documentation necessary but let me know if something needs to be added.

Add py.typed export per PEP 561

---

arrow/locales.py
tests/test_locales.py

Removed "några" from seconds. That is not how we write it.
Just a small wording change for swedish locale.
Added TestSwedishLocale
tox tests fails due to master not having 100% test coverage. (99.80%)

Swedish locale fix

---

arrow/__init__.py

Mypy prevents the implicit reexport, when --no-implicit-reexport is given.
Mypy in combination with `--strict` or `--no-implicit-reexport` prevents implicit reexport, as it was done in `arrow.__init__`. See https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport for details.
This can be either solved by defining `__all__` (this pull request) or by using `as` in the import statements (e.g. `from .api import get as get`).
If you prefer the later version, I can …

Reconfigure arrow/__init__.py to avoid mypy --strict problems

---

arrow/arrow.py
arrow/constants.py
arrow/factory.py
arrow/formatter.py
arrow/locales.py
arrow/parser.py
arrow/util.py

Closes: https://github.com/arrow-py/arrow/issues/819
Closes: #946

Audit all docstrings for style, typos and outdated info

---

arrow/locales.py
tests/test_locales.py

Adds Serbian locale. Serbian actually can be written with both Latin or Cyrillic script - I chose the Latin one here. Not sure if arrow could support both?

Add Serbian locale

---

.pre-commit-config.yaml
arrow/locales.py

Changed type annotation for delta argument of `_format_timeframe` from `Union[float, int]` to `int` since we expect a truncated value as described in https://github.com/arrow-py/arrow/pull/986.
I also bumped `mypy` and other pre-commit dependencies.

Improve _format_timeframe type annotations

---

arrow/constants.py
arrow/locales.py
tests/test_locales.py

Add Zulu locale

---

.pre-commit-config.yaml
requirements-dev.txt
setup.py

Bump dateutil to 2.8.2+ to update tz database.
We gotta figure out which open issues this closes.

Require dateutil 2.8.2+

---

arrow/locales.py

Refactor of Arabic Locale for future dehumanize support. The main reason for this change is that we need a way to convey the actual delta some of those strings represent. Rather than creating a look-up table, or some kind of translation logic, I think it is easier to just have the key be the string representation of an integer. This way, dehumanize call easily interpret this. This will make more sense, when I push the actual dehumanize update PR (after the backlog of locale refactor PRs get merged in …

Refactored Arabic Locale For Dehumanize Support

---

arrow/arrow.py
tests/test_arrow.py

Default to UTC for arrow.fromtimestamp()

Default to UTC for arrow.fromtimestamp()

---

arrow/arrow.py
tests/test_arrow.py

Revert "Default to UTC for arrow.fromtimestamp()"

---

CHANGELOG.rst
requirements-dev.txt
setup.py

Revert dateutil lock back to `>=2.7.0` based on feedback from @pganssle in https://github.com/arrow-py/arrow/pull/1006/files

Revert dateutil lock back to >= 2.7.0

---

arrow/locales.py
tests/test_arrow.py
tests/test_locales.py

Fixing plural of years and days in Hebrew

---

.github/workflows/continuous_integration.yml
requirements-dev.txt
tox.ini

Pypy3 builds recently began failing on our macOS CI runners. Turns out that this is because macOS 11 runners beginning to be used and they lack support for pypy3.6. I needed to update our workflow YAML to manually invoke pypy3.7 to fix this issue.
While I was at it, I also added support for testing against python 3.10 since it is in the final RC stages and will be released very soon.

Fix pypy CI issues and begin testing against Python 3.10

---

arrow/locales.py
tests/test_locales.py

Fix for issue #1062
Closes: #1062

Add support for quarter granularity in Russian (#1062)

---

arrow/locales.py
tests/test_locales.py

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Use Arabic instead of Chinese in `zh-cn` to present numbers for `second` and `week`, to stay the same with other time period and also `zh-tw` and `zh-hk`

chore: align format of cn-zh timeframe

---

tests/test_locales.py

Resolves #1022 
Timeframe testing for multiple variations expanded for the following locales:
- Finnish
- Czech
- Hungarian
- Hebrew
- Sinhala
- Croatian
- Serbian
- Zulu

Expand locale timeframe testing for multiple variations

---

arrow/arrow.py
docs/index.rst

I noticed a Python 2 style print statement in docs, which this PR fixes.

Fix outdated Python 2 print in docs

---

arrow/locales.py

Fixes typo (superfluous comma) in Italian locale and adds week/weeks to Romansh locale

Fix typo in Italian locale, update Romansh locale

---

.github/workflows/continuous_integration.yml
setup.py
tox.ini

Happy to get the chance to finally contribute something to this great project 🎉 
- Added support of Python 3.11. Was pretty easy, no deprecation warnings popped up, at least I didn't see them 😄 
- Added the Python 3.11 classifier
When Python 3.11 will be finally released, then the `dev` suffix for GHA should be removed.

add support for Python 3.11

---

.pre-commit-config.yaml
arrow/arrow.py
arrow/locales.py
arrow/parser.py
setup.cfg
tests/test_locales.py

- Upgrade `mypy` to the newest version, because it has some nice improvements
- The newest `mypy` found a typing issue with `_ordinal_number` for `BengaliLocale`, which is correct, because it would return `None` if a negative number is passed in. This behaviour doesn't fit other locales, like `OdiaLocale` and `TamilLocale` one. I hope I made the right call here to change the return value to an empty string
- Also added error codes to the `type: ignore` comments to not automatically ignore other …

Upgrade mypy

---

.github/workflows/continuous_integration.yml
.pre-commit-config.yaml

- upgrade of pre-commit hooks, except `mypy`
- upgrade GHA of `setup-python` to v4
Split of PR #1129

Upgrade pre-commit hooks and GHA versions

---

tests/test_locales.py

Added plural testcases for the DutchLocale class. Relates to  #1022

Added plurals tests for DutchLocale

---

.github/workflows/continuous_integration.yml
.pre-commit-config.yaml
.readthedocs.yaml
LICENSE
Makefile
arrow/arrow.py
arrow/factory.py
arrow/formatter.py
arrow/locales.py
arrow/parser.py
docs/conf.py
requirements/requirements-docs.txt
requirements/requirements.txt
setup.py
tests/test_arrow.py
tests/test_factory.py
tests/test_formatter.py
tests/test_locales.py
tests/test_parser.py
tox.ini

Fix failing build and drop support for Python 3.6 and 3.7. Update dependencies and add read the docs config.

Fix failing builds and add read the docs configuration

---

arrow/arrow.py
arrow/constants.py
arrow/formatter.py
arrow/locales.py
arrow/parser.py

Removed `typing_extensions` imports which were used for python<3.8, but this package requires python>=3.8.

Remove typing_extensions

---

arrow/arrow.py
docs/guide.rst

Closes #1167.  Added 2 links to the [supported tokens ](https://arrow.readthedocs.io/en/latest/guide.html#supported-tokens) section. One in the `format` api reference and one in the user guide for `format`.

Doc: Make it easier to find the supported tokens for `arrow.format` in the docs

---

pyproject.toml
requirements/requirements-tests.txt
requirements/requirements.txt

types-python-dateutils is only needed when running mypy static type checking; move from runtime to test requirements.

Move dateutil types to test requirements

---

arrow/arrow.py
tests/test_arrow.py
tests/test_factory.py
tests/test_formatter.py
tests/test_parser.py
tests/test_util.py

Python has raised deprecation warning for the use of `datetime.datetime.utcnow()`. The suggestion is to use  `datetime.datetime.now(datetime.UTC)` or similar. 
This PR addresses just by swapping out all datetime utcnow() calls.
I don't think there's anything in documentation to be updated. 
With the example raised in #1178 with `humanize()`: 
Python 3.12: 
```
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for …
```

#1178: changes to address datetime.utcnow deprecation warning

---

arrow/locales.py
tests/test_locales.py

Hello and thanks for this library! While trying to migrate from `humanize` package to `arrow`, I executed
```
>>> arrow.get('2013-05-11T21:23:58.970460+07:00').humanize()
'11 years ago'
>>> arrow.get('2013-05-11T21:23:58.970460+07:00').humanize(locale='el')
'11 χρόνια πριν'
```
The later is printed by `humanize` as
```
'πριν από 11 χρόνια'
```
which is more natural/correct in Greek.
https://github.com/python-humanize/humanize/blob/4da8299fdcf9ad0c56be082b42ee7bee14ee4c4e/src/humanize/locale/el_GR/LC_MESSAGES/humanize.po#L344
Other than that, I fixed Greek abbreviated May accent, so as to be aligned with the full name 15 lines above.

Improve "ago" translation to Greek

---

.github/dependabot.yml

This adds a simple dependabot configuration for updating the used GH Actions.

feat: add dependabot for GH actions

---

arrow/arrow.py
tests/test_arrow.py

Added check_imaginary parameter to the function referring to the issue #1145 
- New Parameter: Added a check_imaginary parameter (defaulting to True), which allows the user to decide whether or not to perform DST/imaginary time checks.
- Skip DST Check: The DST check logic:
block is only executed if check_imaginary is True. If set to False, this check is skipped for improved performance when DST changes are not a concern.
Benefits:
- Backward Compatibility: By default, the method still performs the …

Update shift() for issue #1145

---

arrow/locales.py
tests/test_locales.py

- The expression '그끄제' is rarely used in Korean expressions. Instead, the expression '3일전' is more natural.
- I've corrected the spelling. '재작년', not '제작년', is the right expression.

Modifying Spelling `제작년`, Remove poorly used expressions

---

arrow/arrow.py

Arrow's `__getattr__` provides access to `datetime` attributes that aren't handled by Arrow.
It has this signature:
```python
def __getattr__(self, name: str) -> int
```
It should return `Any`, as not all attributes from `datetime` are `int`s.
For example, in `arrow.now().tzname()`, `tzname` is a function.
I noticed that `__getattr__` implements two undocumented attributes: `week` and `quarter`. The should be split into their own methods, with a docstring.

Fix type signature of Arrow.__getattr__

---

arrow/locales.py
tests/test_locales.py

Adds Macedonian Locale in latin.

Add Macedonian in Latin.

---

arrow/parser.py

Adding docstrings to parser.py (#988)

---

arrow/__init__.py
arrow/formatter.py
tests/test_formatter.py

Adds a FORMAT variable for a more strict RFC3339 where the RFC called for a space for readability and is used by FORMAT_RFC3339, FORMAT_RFC3339_STRICT uses the T separator to adhere with ISO8601 spec.
[RFC Link](https://www.rfc-editor.org/rfc/rfc3339#section-5.6)
```
NOTE: ISO 8601 defines date and time separated by "T".
Applications using this syntax may choose, for the sake of
readability, to specify a full-date and full-time separated by
(say) a space character.
```
Closes #1138

Add FORMAT_RFC3339_STRICT.

---

.gitignore
arrow/arrow.py
arrow/factory.py
arrow/formatter.py
arrow/parser.py
pyproject.toml
requirements/requirements-tests.txt
requirements/requirements.txt
tests/conftest.py
tests/test_arrow.py
tests/test_factory.py
tests/test_formatter.py
tests/test_parser.py
tests/utils.py

- **Fix test errors and deprecation warnings**
- **Migrate to timezone.utc**
- **Migrate from tzlocal to datetime.now().astimezone()**
- **Upgrade dependencies**
Migrate Arrow to use ZoneInfo from PEP 615 standard - https://peps.python.org/pep-0615/. This reduces our reliance on dateutil's tz data base and instead uses the standard library.
Closes: #825
Closes: #1094

Migrate Arrow to use ZoneInfo for timezones

---

arrow/arrow.py
docs/guide.rst
tests/test_arrow.py

Closes #1221 
Add week_start(via kwargs to span) parameter to floor() and ceil()

Add week_start parameter to floor() and ceil()
